#!/usr/bin/env bash
#This script prints out  info on domains and subdomains

print_info(){
    local domain="$1"
    local subdomain="$2"
    local answer=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getlin; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="subdomain")
}

for subdomain in "www" "lb-01" "web-01" "web-02"; do
    if [ -z "$2" ] || [ "$2" = "$subdomain" ]; then
        print_info "$1" "$subdomain"
    fi
done
