#!/usr/bin/env bash
# Get Apache to run on the container and to return a page containing Hello Holberton when querying the root

echo "ServerName localhost" >> /etc/apache2.conf
service apache2 start
