#!/usr/bin/env bash
# Installs Nginx with the specific configurations
sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}
EOF

sudo service nginx restart

