#!/usr/bin/env bash
# installs and configures HAproxy

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo tee -a /etc/haproxy/haproxy.cfg <<EOF
listen webapp 0.0.0.0:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 121887-web-01 100.25.20.65:80 check
	server 121887-web-02 3.95.32.161:80 check
EOF
sudo service haproxy start
