#!/usr/bin/env bash
#Fixes Nginx to listen on port 80

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo nginx -t && sudo service nginx start

