#!/usr/bin/env bash
#This script  configures an Nginx server to listen on port 80 on all IPv4 IPS.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
