#!/usr/bin/env bash
#displays strings using while, if and elif loops
i=1
while [ $i -le 10 ]
do
	(( i++ ))
if [ $i -eq 5 ]
then
	echo $"bad luck"
elif [ $i -eq 9 ]
then
	echo $"good luck"
else
	echo $"Best School"
fi
done
